<a href="https://colab.research.google.com/github/aswin-ar3669/DLA-Python/blob/main/Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow

In [2]:
import tensorflow as tf

# Print TensorFlow version
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.19.0


In [3]:
import tensorflow as tf

# Create a 1D tensor
tensor_1d = tf.constant([1, 2, 3, 4, 5])
print("1D Tensor:", tensor_1d)

# Create a 2D tensor
tensor_2d = tf.constant([[1, 2], [3, 4], [5, 6]])
print("\n2D Tensor:")
print(tensor_2d)

# Perform operations on tensors
# Add two tensors
tensor_sum = tf.add(tensor_2d, 2)
print("\nTensor after addition:")
print(tensor_sum)

# Multiply tensors element-wise
tensor_mul = tf.multiply(tensor_2d, 2)
print("\nTensor after element-wise multiplication:")
print(tensor_mul)

# Matrix multiplication
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])
tensor_matmul = tf.matmul(matrix1, matrix2)
print("\nTensor after matrix multiplication:")
print(tensor_matmul)

# Get the shape and datatype of a tensor
print("\nShape of 2D Tensor:", tensor_2d.shape)
print("Data type of 2D Tensor:", tensor_2d.dtype)


1D Tensor: tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)

2D Tensor:
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)

Tensor after addition:
tf.Tensor(
[[3 4]
 [5 6]
 [7 8]], shape=(3, 2), dtype=int32)

Tensor after element-wise multiplication:
tf.Tensor(
[[ 2  4]
 [ 6  8]
 [10 12]], shape=(3, 2), dtype=int32)

Tensor after matrix multiplication:
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)

Shape of 2D Tensor: (3, 2)
Data type of 2D Tensor: <dtype: 'int32'>
