<a href="https://colab.research.google.com/github/aswin-ar3669/DLA-Python/blob/main/Tensor_Variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

# Create a variable
x = tf.Variable([1, 2, 3], dtype=tf.int32)
print("Variable x:", x)
print("Shape of x:", x.shape)


Variable x: <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
Shape of x: (3,)


In [2]:
# Initialize a variable
v = tf.Variable(5.0)

# Update the variable using the assign() method
v.assign(10.0)
print("Updated value of v:", v.numpy())

# Increment the variable
v.assign_add(2.0)
print("After incrementing:", v.numpy())

# Decrement the variable
v.assign_sub(1.0)
print("After decrementing:", v.numpy())


Updated value of v: 10.0
After incrementing: 12.0
After decrementing: 11.0


In [3]:
# Create variables
a = tf.Variable(3.0)
b = tf.Variable(4.0)

# Perform mathematical operations
c = a * b + 2
print("Result of the operation (a * b + 2):", c.numpy())


Result of the operation (a * b + 2): 14.0


In [4]:
# Create a variable with random initial values
random_var = tf.Variable(tf.random.normal([3, 3], mean=0, stddev=1))
print("Random Variable:")
print(random_var)


Random Variable:
<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[-0.02376165, -1.6541536 , -1.3435816 ],
       [ 0.6635532 ,  0.5395851 ,  0.02276593],
       [ 1.8806179 , -1.1881882 , -0.751397  ]], dtype=float32)>


In [5]:
# Weight and bias initialization for a model
weights = tf.Variable(tf.random.truncated_normal([4, 3], stddev=0.1))
biases = tf.Variable(tf.zeros([3]))

print("Weights:", weights.numpy())
print("Biases:", biases.numpy())


Weights: [[ 0.09681986  0.05761178 -0.06870384]
 [-0.05670349  0.07923395 -0.15701148]
 [-0.09674513 -0.05665919  0.06374558]
 [ 0.01366129 -0.1413955  -0.03654351]]
Biases: [0. 0. 0.]
