<a href="https://colab.research.google.com/github/aswin-ar3669/DLA-Python/blob/main/Tensor_Operation3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

# Create a tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extract a slice
slice_ = tensor[1:, :2]  # From row 1 onwards, first two columns
print("Extracted Slice:\n", slice_)


Extracted Slice:
 tf.Tensor(
[[4 5]
 [7 8]], shape=(2, 2), dtype=int32)


In [ ]:
# Create a tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extract non-contiguous slices (rows 0 and 2)
non_contiguous_slices = tf.gather(tensor, [0, 2])
print("Non-Contiguous Slices:\n", non_contiguous_slices)


Non-Contiguous Slices:
 tf.Tensor(
[[1 2 3]
 [7 8 9]], shape=(2, 3), dtype=int32)


In [ ]:
# Create a tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Find the maximum element
max_element = tf.reduce_max(tensor)
print("Maximum Element:", max_element.numpy())


Maximum Element: 9


In [ ]:
# Find the minimum element
min_element = tf.reduce_min(tensor)
print("Minimum Element:", min_element.numpy())


Minimum Element: 1


In [ ]:
# Create two tensors
tensor1 = tf.constant([1, 4, 7])
tensor2 = tf.constant([3, 2, 8])

# Element-wise minimum
min_tensor = tf.minimum(tensor1, tensor2)
print("Element-wise Minimum:", min_tensor.numpy())

# Element-wise maximum
max_tensor = tf.maximum(tensor1, tensor2)
print("Element-wise Maximum:", max_tensor.numpy())


Element-wise Minimum: [1 2 7]
Element-wise Maximum: [3 4 8]


In [ ]:
# Create two tensors
tensor1 = tf.constant([[1, 2], [3, 4]])
tensor2 = tf.constant([[5, 6], [7, 8]])

# Concatenate along rows (axis=0)
concat_rows = tf.concat([tensor1, tensor2], axis=0)
print("Concatenated along rows:\n", concat_rows)

# Concatenate along columns (axis=1)
concat_cols = tf.concat([tensor1, tensor2], axis=1)
print("Concatenated along columns:\n", concat_cols)


Concatenated along rows:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)
Concatenated along columns:
 tf.Tensor(
[[1 2 5 6]
 [3 4 7 8]], shape=(2, 4), dtype=int32)
