<a href="https://colab.research.google.com/github/aswin-ar3669/DLA-Python/blob/main/Tensor_Operations1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import tensorflow as tf

# Create a variable
var = tf.Variable([1, 2, 3, 4], dtype=tf.float32)
print("Variable:", var)

# Convert variable to constant
const = tf.convert_to_tensor(var)
print("Converted to constant:", const)


Variable: <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>
Converted to constant: tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)


In [7]:
# Create a constant
const = tf.constant([5, 6, 7, 8], dtype=tf.float32)
print("Constant:", const)

# Convert constant to variable
var = tf.Variable(const)
print("Converted to variable:", var)


Constant: tf.Tensor([5. 6. 7. 8.], shape=(4,), dtype=float32)
Converted to variable: <tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([5., 6., 7., 8.], dtype=float32)>


In [8]:
# Create a tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
print("Original Tensor:")
print(tensor)

# Reshape to (3, 2)
reshaped_tensor = tf.reshape(tensor, [3, 2])
print("\nReshaped Tensor (3x2):")
print(reshaped_tensor)


Original Tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Reshaped Tensor (3x2):
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [9]:
# Create a 2D tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
print("Original Tensor:")
print(tensor)

# Flatten the tensor
flattened_tensor = tf.reshape(tensor, [-1])
print("\nFlattened Tensor:")
print(flattened_tensor)


Original Tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Flattened Tensor:
tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [10]:
# Create a tensor
tensor = tf.constant([1, 2, 3, 4, 5, 6, 7, 8])

# Reshape to (2, 4)
reshaped_tensor1 = tf.reshape(tensor, [2, 4])
print("Reshaped Tensor (2x4):")
print(reshaped_tensor1)

# Reshape to (4, 2)
reshaped_tensor2 = tf.reshape(tensor, [4, 2])
print("\nReshaped Tensor (4x2):")
print(reshaped_tensor2)

# Reshape with -1 (let TensorFlow infer one dimension)
reshaped_tensor3 = tf.reshape(tensor, [-1, 2])  # Automatically infer rows
print("\nReshaped Tensor (-1, 2):")
print(reshaped_tensor3)


Reshaped Tensor (2x4):
tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)

Reshaped Tensor (4x2):
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)

Reshaped Tensor (-1, 2):
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)
